### ISSUE TITLE
Fix the CI

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#100]
@Niols Sorry it seems I broke the CI but I don’t know why. The error is

```
File "tests/runner/engine.ml", line 24, characters 11-16:
Error: Unbound record field input
```

Do you have an idea why I didn’t receive this error on my machine and how it is produced?

**Comment by Niols** [comment]
Yes, idk, I can't reproduce it either. This is weird. I'll investigate.

**Comment by benozol** [comment]
This happens already since 39652920b5c6a6d59844ada2cc022377b348185d: https://travis-ci.org/colis-anr/colis-language/jobs/525577752

**Comment by Niols** [comment]
Got it. It wasn't our fault. ppx_protocol_conv changed it's API. I'll push a fix shortly.

**Comment by Niols** [comment]
Problem solved.

**Comment by benozol** [comment]
Nice, thanks!
