### ISSUE TITLE
Extend colis with and/or operators on booleans

### ISSUE THREAD

**Issue by yurug** [colis-anr/colis-language#104]
To improve the readability of generated colis programs, we should avoid the nesting of if-then-else which results from the encoding of or/and operators.

Could we extend colis with these boolean operators?

**Comment by benozol** [comment]
Not sure if we want to change the CoLiS semantics and the concrete and symbolic interpreter just to improve readability of generated programs. Maybe it would be sufficient to change the pretty printer?
