### ISSUE TITLE
symbolic utilities : list of options that are ignored

### ISSUE THREAD

**Issue by treinen** [colis-anr/colis-language#109]
The signature of a module that implements a particular symbolic utility should  also contain
a list of options that we know that we can safely ignore them (like -v, -h, etc)

**Comment by Niols** [comment]
I'm not sure I see what you mean: do you want that the interface of a symbolic utility carries a `val ignored_options : string list`? Or do you just mean that the function `interp` should handle these options correctly and document them?

**Comment by treinen** [comment]
What I wrote is not the way this should be done.

What I really meant  is : we need some general functions that help in handling options of utilities, like ignoring those that are not relevant, identifying long and short form of the same option. Maybe we can reuse some stuff from the command-analyzer of shstats.

**Comment by Niols** [comment]
Yes, that's indeed something we need. For rm, I added a dirty fix for now, but it would be much better to have something generic.

I was planning to have a look at what already existed. I will come back with something.

— Nicolas Jeannerod
