### ISSUE TITLE
Add a type "program", wrapper around "statement"?

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#11]
It would be

    type program = statement

in our case (it could be `statement list` but I don't think it adds anything). It would not have a behaviour as an output but only true|false.

It's a small change, but it would make things a bit cleaner imho.

**Comment by benozol** [comment]
Good idea – and it’s already in the parser:
https://github.com/colis-anr/symbolic/blob/7dedc62e6e3129c2a904067c9999f139278c8161/src/colisParser.mly#L23-L25
