### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#12]
Apparently, for now, we want to put everything in the same executable. This is fine to me. However, as it will have to do a lot of things, the command line will be slightly complicated and deserves that we think a bit about it.

What I would like to be able to do with the tool:
- handle colis and shell inputs the same way (this is already what you added with `-shell` and `-colis`)
- be able to only parse (I don't know about colis scripts, but it would be useful to measure how many shell scripts are accepted by our tool without executing anything)
- be able to print colis or shell. This would allow us to see what the translation/s does/do
- be able to execute in a concrete or symbolic way

Question:
- do we want to handle several files at once? I'm not sure if it's really useful (we can always have a wrapper around the tool) and it makes things a bit more complicated.

Maybe:
- `--colis` (to specify the format of the input)
- `--shell` (the default?)
- `--print-colis` (on standard output?)
- `--print-shell` (or maybe just `--print` and we use the selector `--colis`|`--shell` to choose the other one? But then, maybe print is a bad name)
- `--concrete` (the default, I'd say? Well, for now, we don't have much choice)
- `--symbolic`

**Comment by Niols** [comment]
- `--realworld`? to be plugged to utilities found in the PATH

**Comment by benozol** [comment]
> --realworld? to be plugged to utilities found in the PATH

Agreed, this would be useful.

> --print-shell (or maybe just --print and we use the selector --colis|--shell to choose the other one? But then, maybe print is a bad name)

Two printing options matching the parsing options are fine I think.

---

What do you think of the following command line syntax? Defaults are marked with asterisks.
```
./colis [--help | [--run* [--realworld] [--compare[=ORACLE]] | --run-symbolic | --print-colis | --print-shell] [--shell* | --colis] FILE ]
   --run                Concrete execution
   --run-symbolic       Symbolic execution (not yet implemented)
   --print-colis        Print the CoLiS script
   --print-shell        Print the Shell script
   --realword           Use system utilities in concrete execution
   --compare[=ORACLE]	Execute of FILE and compare results from file ORACLE (or from file "$(basename FILE .cls .sh).oracle")   
   --shell              Use the Shell parser
   --colis              Use the CoLiS parser

```

We could also use subcommands (like `colis concrete`, `colis print`, etc) but I am not sure if this makes the CLI really easier.

**Comment by Niols** [comment]
I like this command line. Maybe the following comments:
- do you really want to avoid having a default between `--shell` and `--colis`?
- same question for `--run` and `--run-symbolic`
- I would like to take `--compare` out of the tool. It's just comparing the outputs and it only makes sense for testing, I don't think it has anything to do with the tool itself
- The first line is really complicated to read ^^ I wonder how it could be made easier. Maybe by using several lines?

I can take care of modifying `concrete_colis` to use Arg and implement this interface.

**Comment by benozol** [comment]
> do you really want to avoid having a default 

No, defaults are fine and I marked them by asterisks

> I would like to take --compare out of the tool.

Agreed, and I was not really sure where to locate the option.

> I can take care of modifying concrete_colis to use Arg and implement this interface.

`concrete_colis` is already using `Arg` from the stdlib – or do you mean `Cmdliner.Arg`?

**Comment by benozol** [comment]
> I would like to take --compare out of the tool.

Then the output of `./colis -concrete` should probably be just the stdout. In that case, however, the comparison couldn’t be just a plain `diff` with the oracle anymore because we also want to compare the result value. Do you have an idea? Result in first line of oracle and diff with `tail -n+2`? Result encoded in filename?

**Comment by Niols** [comment]
Oh, no, I meant Arg from the stdlib. I find that sufficient for most simple uses.

OK, do you want me to take care of that? I can have a PR readdy this afternoon

**Comment by Niols** [comment]
Well, the output of `./colis -concrete` could be just stdout. And the exit code would be 0 in case of success, 1 in case of error and >1 in case of problems (in currently use 2 for syntax error and 3 for conversion error but we should document these).
