### ISSUE TITLE
Drop support for OCaml < 4.08.0?

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#127]
It is not necessarily my habit to drop support for "old" versions of OCaml as soon as possible. However, I think it has been several times in this project that I tried to use 4.08 features. In the meantime, OCaml 4.08.0 has reached Debian stable. And unstable/testing are in 4.08.1. Could we and should we drop older versions of OCaml?

@benozol @treinen @claudemarche Any opinion?

**Comment by treinen** [comment]
The version of OCaml in debian stable is 4.05.0. OCaml 4.08.1 is in
debian testing (and unstable).

I would be OK to require versions >= than those in debian testing. There 
are other parts of the toolchain that do already require that (why3, for
instance).

-Ralf.
-- 
Ralf Treinen
Institut de Recherche en Informatique Fondamentale
Pôle Preuves, Programmes et Systèmes
Université de Paris
http://www.irif.fr/~treinen/

**Comment by benozol** [comment]
Why3 also has the Ocaml version from Debian stable as lowest requirement, 4.05.

But I am fine with focussing on Ocaml from Debian testing, i.e. 4.08. This would also reduce stress from the CI.

**Comment by Niols** [comment]
I would say that, yes. It's not like we're really targetting instability of our tool on Debian stable. Maybe we will one day, but the next version is for next year.
