### ISSUE TITLE
Avoid replaying the proofs in all contexts for a faster CI?

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#128]
Everything is in the title. Currently, during the CI, we replay the proofs in all contexts (that is in all versions of OCaml). This is probably pointless, isn't it? Couldn't we just replay the proofs in one context?

@benozol What do you say? I can make the change if that sounds good to you.

**Comment by benozol** [comment]
Yes please. I have tried that once in branch [faster-ci](https://github.com/colis-anr/colis-language/commits/faster-ci)) but it didn't work due to limited knowledge about travis

**Comment by Niols** [comment]
OK, I'll do that after the whole merge.
