### ISSUE TITLE
Remove hints in constraint variables

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#129]
I don't think we ever use the hints anymore. The graphical printing of constraints doesn't need them anyways. And we always compute them from the path so that can be done at the time of printing the constraints, and not in the specifications. This would then remove a few lines in specifications, and a few traversals of lists (that are used to find the last element of a path). This should be a quick change and I can take care of it. After the whole PR situation is sorted out, of course; let's not add noise.

@benozol Any thoughts?

**Comment by benozol** [comment]
Very good, `last_comp_as_hint` will not be missed
