### ISSUE TITLE
Create `src/constraints/iclause.mli`

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#17]

**Comment by Niols** [comment]
1. No, it's not, and it should be, you are right.
2. I would write all the functions of type `t -> disj` and have a bind (monadic or not, as long as it's convenient to use)
3. I would like an `exists` function of type `(Variable.t -> Clause.t -> Clause.disj) -> Clause.t -> Clause.disj`, probably?

**Comment by benozol** [comment]
1-2. Good
3. Still, does the continuation function require the `Clause.t` argument? 

> We probably should. I was thinking about having a submodule for it, but it will change really fast, so it might not be the best idea. I'd just copy the directory inside src/ftwu, WDYT?

Sounds good.

**Comment by Niols** [comment]
Notes from the meeting:
- the type `disj` should be abstract
- all the functions should have type `... -> t -> disj`
- the functions `exists` and `>>=` should be defined here
- the names for abs, feat, etc. should be the full names
- what about adding helpers for similarities except in singletons and empty directories? maybe not straight in the interface
- there should be several interfaces:
  - the "low-level" iclause interface
  - a "medium-level" interface working on pathes and roots, just like the one described in the PDF file for specifications, used to write specifications
  - the "high-level" interface of specifications that the symbolic engine will use

@benozol Anything else? I will try to send you a draft today or tomorrow in a new PR

**Comment by benozol** [comment]
>     * the functions `exists` and `>>=` should be defined here

OK, but maybe we can keep the low-level `exists` (as `close_exists`?) to create `exists` with other return types (e.g., `exists_in_state : (variable → state list) → state list)`? (Alternatively to your suggestion to parametrize `clause` and `disjunction` by some `'a`)

>     * the names for abs, feat, etc. should be the full names

And rename `t` to `clause` and/or `disj` to `disjunction`? And `Clause` to …?
> 
>     * what about adding helpers for similarities except in singletons and empty directories? maybe not straight in the interface

I think that `Set.empty` and `Set.singleton` are good enough

>     * there should be several interfaces:
>       
>       * the "low-level" iclause interface
>       * a "medium-level" interface working on pathes and roots, just like the one described in the PDF file for specifications, used to write specifications

Hey that works nicely:

```ocaml
let rec similarity_path x p y cls =
  match p with
  | [] -> failwith "similar_path"
  | [f] -> [cls] >>= Clause.feat x f y
  | f :: p ->
    exists ~hint:(Variable.hint x) @@ fun x' ->
    exists ~hint:(Feature.to_string f) @@ fun y' ->
    [cls] >>=
    Clause.feat x f x' >>=
    Clause.feat y f y' >>=
    similarity_path x p y
```

>       * the "high-level" interface of specifications that the symbolic engine will use

>  Anything else? 

When `disjunction` and `>>=` are abstract, we’ll need a monadic `return/pure/singleton : clause -> disjunction = fun cls -> [cls]`

**Comment by Niols** [comment]
> > ```
> > * the names for abs, feat, etc. should be the full names
> > ```
> 
> And rename `t` to `clause` and/or `disj` to `disjunction`? And `Clause` to …?

I tried with full names and I find that quite verbose… Still, I can do it if we really think it's worth it. `t` could be renamed to `conjunction` or `conj`.

> > ```
> > * there should be several interfaces:
> >   
> >   * the "low-level" iclause interface
> >   * a "medium-level" interface working on pathes and roots, just like the one described in the PDF file for specifications, used to write specifications
> > ```
> 
> Hey that works nicely:
> 
> ```ocaml
> let rec similarity_path x p y cls =
>   match p with
>   | [] -> failwith "similar_path"
>   | [f] -> [cls] >>= Clause.feat x f y
>   | f :: p ->
>     exists ~hint:(Variable.hint x) @@ fun x' ->
>     exists ~hint:(Feature.to_string f) @@ fun y' ->
>     [cls] >>=
>     Clause.feat x f x' >>=
>     Clause.feat y f y' >>=
>     similarity_path x p y
> ```

Yes, it's pretty easy to implement using the lower one and it makes the specifications easier to read, probably. Except I'd maybe use the same names in `Clause` and `Clause.WithPath` (please find an other name), that is:

```ocaml
val sim : Var.t -> Feat.Set.t -> Var.t -> conj -> disj
val sim_one : Var.t -> Feat.t -> Var.t -> conj -> disj
val WithPath.sim_one : Var.t -> Path.t -> Var.t -> conj -> disj
```

And we would **always** use the `WithPath` module from the outside. So maybe, this could actually be the interface, the version with features being hidden. Would that look nice to you? I think I like it.
 
> > ```
> >   * the "high-level" interface of specifications that the symbolic engine will use
> > ```
> 
> > Anything else?
> 
> When `disjunction` and `>>=` are abstract, we’ll need a monadic `return/pure/singleton : clause -> disjunction = fun cls -> [cls]`

By the way, what type would you want for `>>=`? `disj -> (conj -> disj) -> disj`? I was thinking about having a name for the type `conj -> disj` (maybe `literal`, so that `feat`, `sim`, etc. look like constructors?) and a function to combine them of type `literal -> literal -> literal`. Maybe:

```ocaml
let (&) l1 l2 c = l1 c >>= l2
val (&) : literal -> literal -> literal
```

**Comment by benozol** [comment]
> I tried with full names and I find that quite verbose… Still, I can do it if we really think it's worth it. `t` could be renamed to `conjunction` or `conj`.

I am fine with abbreviations, I thought you liked the long forms. Only `t` was just a bit too short IMO

> Yes, it's pretty easy to implement using the lower one and it makes the specifications easier to read, probably. Except I'd maybe use the same names in `Clause` and `Clause.WithPath` (please find an other name), that is:
> 
> ```ocaml
> val sim : Var.t -> Feat.Set.t -> Var.t -> conj -> disj
> val sim_one : Var.t -> Feat.t -> Var.t -> conj -> disj
> val WithPath.sim_one : Var.t -> Path.t -> Var.t -> conj -> disj
> ```
> 
> And we would **always** use the `WithPath` module from the outside. So maybe, this could actually be the interface, the version with features being hidden. Would that look nice to you? I think I like it.

For similarity, the path-lifted version will be quite common but I am not sure for the other constraints. Also, I do not know if can really separate the medium and hight-level interface.

> > When `disjunction` and `>>=` are abstract, we’ll need a monadic `return/pure/singleton : clause -> disjunction = fun cls -> [cls]`
> 
> By the way, what type would you want for `>>=`? `disj -> (conj -> disj) -> disj`? I was thinking about having a name for the type `conj -> disj` (maybe `literal`, so that `feat`, `sim`, etc. look like constructors?) and a function to combine them of type `literal -> literal -> literal`. Maybe:
> 
> ```ocaml
> let (&) l1 l2 c = l1 c >>= l2
> val (&) : literal -> literal -> literal
> ```

I agree a point-free implementation is even nicer!  `(>=>)` seems to be common for monadic composition, and then we can

```ocaml
type m = Clause.t -> Clause.disj (* TODO rename *)
let pure : m = fun cls -> [cls]
let (>>=) disj f = List.(map f disj |> flatten)
let (>=>) f1 f2 = fun cls -> pure cls >>= f1 >>= f2
let lift f : m = fun cls -> pure (f cls)

let exists : ?hint:string -> (Variable.t -> m) -> m =
  fun ?hint k ->
    let v = Variable.fresh ?hint () in
    k v >=>
    lift (Clause.exists [v])

let rec similarity_path x p y : m=
  match p with
  | [] -> failwith "similar_path"
  | [f] -> Clause.feat x f y
  | f :: p ->
    exists ?hint:(Variable.hint x) @@ fun x' ->
    exists ~hint:(Feature.to_string f) @@ fun y' ->
    Clause.feat x f x' >=>
    Clause.feat y f y' >=>
    similarity_path x p y
```
