### ISSUE TITLE
Seperate return code and behaviour in concrete semantics?

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#25]
Currently, the return code and behaviour in the concrete semantics are kept together by a `type behaviour = BNormal bool | BExit bool`), just like in @Niols' previous version.

In the concrete interpreter, however, return code and behaviour are separated: the return code is a mutable field in the state and the behaviour is reflected by the OCaml behaviour (normal value or raised exception).

I am wondering if this separation is actually closer to *The Truth* and should also be reflected in the inductive specification by putting the return code in the `context` (and removing `previous_result` from `input`). It may even simplify the proofs. WDYT? Did you already try that?

**Comment by benozol** [comment]
OK maybe that’s not going to help a lot in the proofs (at least this isn’t an issue sofar).

**Comment by Niols** [comment]
Actually, I haven't really understood what you meant. Did you mean to have `type behaviour = bool * kind and kind = BNormal | BExit`?

**Comment by benozol** [comment]
I was thinking about something like the following:
```mlw
type input = { …; (* remove previous_result *) }
type context = { …; result: bool }
type behaviour = BNormal | BExit
inductive eval_instruction input context state instruction state context behaviour
```
For any `eval_instruction inp ctx sta ins sta' ctx' b`, the previous return code is `ctx.result` and the return code of the evaluation of `ins` is `ctx'.result`.

This corresponds closer to the signature of the interpreter where `state` and `context` are mixed in a (mutable) `Interpreter.state` and the behaviour is reflected by the OCaml behaviour. But I am really no sure if this solves any problem.

**Comment by Niols** [comment]
I could make the semantics shorter/clearer though, couldn't it?
