### ISSUE TITLE
Add functions to the CoLiS language

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#27]
Functions should be added to the CoLiS language to define macros in the specification of shell commands. (By constrast, functions in the Debian corpus can generally be inlined.)

There are two possibilities for adding functions:
1. Function definitions precede the instruction of a `program`; a function environment is added in the evaluation context; and function are called by their name (“the usual way”). E.g.:
```mlw
type instruction = …
| TFunctionCall string list_expression
type function_definition = string * instruction
type program = list function_definition * instruction
```
2. Function definitions are inlined into the call site, which is easy because the shell parser already creates a function environment. E.g.:
```mlw
type instruction = …
| TFunctionCall instruction list_expression
```

Evaluation of 1. allows for defining recursive functions (which is at least necessary for the specification macro of `rm -rf`) but discards the information about function bindings that was already generated by the shell parser. Evaluation in 2. is trivial but prevents the definition of for recursive functions, .

**Comment by benozol** [comment]
Given that the main motivation to add functions is the definition of command macros – which are potentially recursive – we should go with 1.

**Comment by benozol** [comment]
Function definitions in the instructions would allow for local functions. Do local Shell functions conform to POSIX? Are there occurrences in the Debian corpus? Maybe it wouldn’t complicate the semantics either… Where do you see benefits?

**Comment by Niols** [comment]
I wasn't thinking about local functions. But this is how shell works: a function definition is a compound command like any other and can occur pretty much anywhere. When it is encountered, it causes the function environment to be changed. For instance:

```shell
if ...; then
    ls () {
        echo hahaha
    }
fi
ls
```

is perfectly valid code. Depending on the execution of the condition, the last call to `ls` is either the function or the utility. Note that the converter wont be able to track down those uses. It will probably only allow for function definitions at toplevel. Still, one can intertwine function definitions with other pieces of code, like so:

```shell
my_function () {
    some code doing something
}

some code using 'my_function'

my_function () {
    some code doing something else
}
```

but I guess this could be rewritten (carefully, but it's not that hard) to something with all the definitions at the top of the file.

Anyway, it's probably cleaner to have all the function definitions at the beginning (that is, in the `program` type). I'll take care of the conversion.

**Comment by Niols** [comment]
Alright, let's do this, then. I can start working on this, but I'll need you to modify the type however you like before actually having the conversion. What about things like `$@` though? Do you plan on having them in the semantics (like `ICallArgs`)? That seems rather complicated to me. So I'm not even sure the conversion really wants to convert Shell functions to CoLiS functions
