### ISSUE TITLE
Concrete interpreter should be fully imperative

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#5]
Nicolas’ old implementation (and the one in this repo until c6577824b16) is a compromise between functional and imperative features by using a mutable stdout but an immutable variable environment, where changes are reflected in the result value.

To make a clear commitment to an imperative implementation, the variable environment should be part of the mutable interpreter state.

See NOTES[Concrete interpreter type].

**Comment by benozol** [comment]
A proposal is available in branch `fully-imperative-concrete`. I guess this implementation lies at the very opposite end of the functional/imperative spectrum than the inductive specification in `semantics.Semantics`.

The state record is fully mutable:

https://github.com/colis-anr/symbolic/blob/d55b45781ba28ffa6298beed4952fe37e1f36ba7/src/concrete/interpreter.mlw#L34-L40

* The state is composed of non-mutable fields of references. This provides as a simple solution to ignoring changes in some fields (e.g., the variable environment for subshells), or dealing with fields differently (e.g., stdout in a subshell in a string), without having to switch back the old field value after use.
* Even the return value is in the state and serves as the value of `$?`.

The resulting signature of the interpreter function is then very simple:

https://github.com/colis-anr/symbolic/blob/d55b45781ba28ffa6298beed4952fe37e1f36ba7/src/concrete/interpreter.mlw#L112-L120

@claudemarche @claudemarche What do you think?

**Comment by Niols** [comment]
I like it. Will this make the proofs harder? By how much? (note that this does not mean we shouldn't do it)

**Comment by benozol** [comment]
That’s also why I hesitated a bit. But maybe this isn’t even the case because the same information that was previously available in two variables `state` and `state'` is now available in `old state` and `state`.

**Comment by Niols** [comment]
Hum, hopefully, yes, it wont change the proof obligations that much

**Comment by benozol** [comment]
BTW we previously discussed adding a suffix-like function to the stdout module  to avoid the existentials in the proofs (like `stdout = suffix (old stdout) stdout` instead of `∃ s. stdout = old stdout ^ s`).

Alternatively, we could add the stdout to the state in the inductive definition to track the stdout *before* and *after* the execution. This corresponds closely to the implementations (the one you published and the one proposed in my branch). Or is there another advantage to assume in the inductive definition that the stdout is initially empty?

**Comment by Niols** [comment]
I am not sure I understand all you just say. However, no, there is no advantage to assume that stdout starts empty (as far as I remember)

**Comment by benozol** [comment]
Currently, `eval_stmt` is defined as:
```
type state = { … }
type output = { stdout: stdout; behaviour: behaviour }
inductive eval_stmt input context state statement state context output = …
```
I would propose instead:
```
type state = { …; stdout: stdout }
(* No output type required *)
inductive eval_stmt input context state statement state context behaviour = …
```
For an `eval_stmt inp ctx sta stm sta' ctx' bhv` we have `sta.stdout` and `sta'.stdout` in correspondence with `!(old sta.stdout)` and `!(sta.stdout)` in the interpreter.

**Comment by Niols** [comment]
Which would make the proofs much easier, right?

**Comment by benozol** [comment]
I hope so!

**Comment by Niols** [comment]
Great! Can't wait for the PR ;-)

**Comment by Niols** [comment]
Hum, I guess this can be closed, but I'll let you do it as I'm not entirely sure.
