### ISSUE TITLE
Proove properties of symbolic execution

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#55]
- [ ] under-appoximation
- [x] termination (requires loop limit #56 and stack size)
- [x] over-approximation

**Comment by Niols** [comment]
@benozol I think now we have under-approximation, right?

**Comment by benozol** [comment]
No we don't have under-approximation. It wouldn't be too difficult to prove (just the other direction of an equivalence) but it does not make a lot of sense because the utilities don't comply to it, right?

**Comment by Niols** [comment]
Oh, I thought we had it. Maybe just the IMP implementation then? No, indeed, utilities don't comply to it anyway. Should we close this issue in any case?

**Comment by benozol** [comment]
Yes
