### ISSUE TITLE
Test suite and continous integration

### ISSUE THREAD

**Issue by claudemarche** [colis-anr/colis-language#6]
The former test suite from the Gforge repository should be reused, for replaying tests manually and also for continous integration.

* import the former `.cls` files and adapt their concrete syntax
  though, we can forget about the tests that involve `date` or commands that modify the filesystem: `mkdir` and such
* import the corresponding `.oracle` files as is
* implement in OCaml a check of conformance between the result of concrete interpreter and the contents of oracle files
* add a continous integration process that checks the conformance of all tests with their oracles

**Comment by Niols** [comment]
Linked to #9. I can take care of the continuous integration part as I'm used to setting that kind of things up (with Docker + Travis for instance)

**Comment by Niols** [comment]
Having Docker is actually much more useful than for testing only. Especially considering that Why3 is not that common to have on one's machine and not that easy to setup in the right conditions
