### ISSUE TITLE
Integrate Morsmall parser

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#7]
The shell parser can be activated with command `./concrete_colis -shell FILENAME` but the implementation is actually missing.

The functions `{FromColis, FromShell}.parse` currently have a signature `filename:string -> statement`. Maybe we should change it to a more general argument type that works with files and strings of code.

**Comment by Niols** [comment]
I'm already on it. PR coming soon (this afternoon). However, we will then require Morsmall


-------- Message d’origine --------
De : Benedikt Becker <notifications@github.com>
Envoyé : 3 octobre 2018 10:51:15 GMT+02:00
À : colis-anr/symbolic <symbolic@noreply.github.com>
Cc : Nicolas Jeannerod <niols@niols.fr>, Assign <assign@noreply.github.com>
Objet : [colis-anr/symbolic] Integrate Moresmall parser (#7)

The shell parser can be activated with command `./concrete_colis -shell FILENAME` but the implementation is actually missing.

The functions `{FromColis, FromShell}.parse` currently have a signature `filename:string -> statement`. Maybe we should change it to a more general argument type that works with files and strings of code.

**Comment by Niols** [comment]
See #8

**Comment by Niols** [comment]
I've read about submodules and it might be a way to do what we want. Except that the commands are a bit painful:
- Cloning is now: `git clone --recursive`
- Pulling when the version of the submodule has changed should be `git pull && git submodule sync --recursive && git submodule update --init --recursive` and sadly, there is no easier way to do it

However, Dune has no problem with that and is perfectly fine with building the two required libraries.

**Comment by Niols** [comment]
@benozol I can do that right now if you still think it's the best option. I think it's OK. Not the best, but probably the least bad in order to satisfy everyone.

I'd probably add a directory "submodules" (or "external"?) at the root so that they don't appear in the source tree, which might be weird (what do you think about that?).

Compilation will work nicely with submodules that compile with Dune. However, you wanted to add why3-ide as a submodule too, right? I don't really know how to achieve that in a clean way

**Comment by Niols** [comment]
After the merge of #36 into master, I'll just copy Morsmall from its git repo to `lib/morsmall` for now. I think it's the simplest solution. And if it is stable enough in the end, I'll just move it back to its repository.

**Comment by benozol** [comment]
I have currently a similar issue in #28 : I want to fix the version of Why3 used in the proofs to a given commit (during development).  I think this could be done by `opam pin` in the Dockerfile, or by a git submodule. (Copying it to `lib/why3` doesn’t make much sense I guess.) What do you think?

**Comment by Niols** [comment]
I'm fine with `opam pin`, that's how I currently do it in the Dockerfile (https://github.com/colis-anr/colis-language/blob/master/Dockerfile#L19). We could also add a small line in the README.

**Comment by Niols** [comment]
@benozol I guess we can close this one, now that we just decided that it was pinned?

**Comment by benozol** [comment]
Yes agreed.
