### ISSUE TITLE
Incompleteness behaviour for unknown utilities and options

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#70]
Currently, the behaviour of unknown utilties and options is determined by the command-line option `--fail-on-unknown-utilities`: By default, the concrete and symbolic interpretation results in an error with a message in stdout. With the option enabled, the interpreter raises exception and fail with return code  7 or 8.

With #60 we can use the `failure` behaviour, which captures execution outside the coverage of the symbolic execution, for unknown utiltiies and options as well. Consequently, we can discard the option `--fail-on-unknow-utilities`, and make failure the standard for the concrete interpreter without `--real-word`.

**Comment by Niols** [comment]
That has been solved by #114, hasn't it?

**Comment by benozol** [comment]
Yes!
