### ISSUE TITLE
Add utility `which`

### ISSUE THREAD

**Issue by Niols** [colis-anr/colis-language#73]
Hey @benozol 

I'm thinking of adding the `which` utility. It's no hard work *per se*, but I need to know how to proceed. I guess it is a bit related to #33 in a way. At some point, we will have to implement utilities that depend on the state of the environment variables. This implies several questions:

- How do we want to represent utilities that read the environment? Should the function `SymbolicUtilities.interp` take the environment as well? And maybe give it only to the utilities that require it?

- Do we model the "export" mechanism of the Shell? "export" is actually [the number 1 target of the conversion now](http://ginette.informatique.univ-paris-diderot.fr/~niols/colis-covering-report/#conversion-error) and it would probably be more accurate.

- In #33, you suggested that `cd` could be implemented as a utility changing the environment. How would we model that? But maybe that's more a discussion for #33.

**Comment by claudemarche** [comment]
I am willing to implement that, but as you say a preamble is to pass the context to utilities, otherwise I cannot access to current value of PATH.
I will commit first a temporary over-approximation that just specified as returning 0 or 1

**Comment by Niols** [comment]
Wait! I'm already working on that on the `which` branch. I'll push that in a PR if you want to talk about it.

**Comment by claudemarche** [comment]
Well, if you are already working on that you should have assigned yourself this issue ;-)
Moreover, on yesterday's compte-rendu it was my name that was in front of that...
I have also a PR in progress now...

**Comment by Niols** [comment]
Yeah, sorry, I had not seen that (both that I wasn't assigned here and the compte-rendu)

**Comment by Niols** [comment]
Actually, most of my changes are around `symbolicUtilities` to prepare for `which`, so the two PRs should almost be compatible: #76 adds the environment to `SymbolicUtilities.interp` and tries to make the helpers `success_case` and `error_case` richer so that one can specify a success case that prints something (which is important for the `which`).

**Comment by claudemarche** [comment]
There are not fully compatible since you changed the OCaml types of success_case and error_case.
Never mind, I'll wait for your changes coming into master

**Comment by claudemarche** [comment]
Still, I propose to remain assignee for this issue specific to `which`, and not you.

**Comment by Niols** [comment]
But there was at least a question remaining: at some point, we will need to compose specifications. This will be useful for commands with multiple arguments (`mkdir`, for instance) and also for complex commands. In the case of which, it will probably be necessary to describe: "if it exists in the first component of PATH, then we print this, else we try the second component, etc.".

In the paper document, we used a CoLiS-like syntax to describe such utilities. But if we want to have the same thing in our tool, that means profound changes—which is alright if necessary. What is more worrying in my opinion is that it creates an interdependence between the utilities and the symbolic engine (the symbolic engine calls the utilities that may return *any* CoLiS script that has to be executed again) and makes the termination proof complicated if not invalid (actually, such a process may very well not terminate).

An other way would be to have helpers to compose specifications. And in particular the "if". But that means duplication with the symbolic engine. I was about to go for this second option, but I wasn't really sure. Any thoughts, @claudemarche, @benozol?

**Comment by Niols** [comment]
> There are not fully compatible since you changed the OCaml types of success_case and error_case.

I only added an optional argument `?output:string` to specify the output of a specification case, so this should remain compatible. However, `interp` now takes an additional argument which makes indeed the PRs non-compatible (the change is fairly small, though).

**Comment by Niols** [comment]
>  Never mind, I'll wait for your changes coming into master

I think that the PR #76 adds useful stuff for later. But I'd like @benozol's opinion since I'm touching a part of the code that he wrote and that he understands much better than me.

> Still, I propose to remain assignee for this issue specific to `which`, and not you.

I agree. Technically, I haven't touched `which` yet! ;-)

**Comment by benozol** [comment]
> makes the termination proof complicated if not invalid

For termination, we would need a limit the stack size anyway, and complex utilities returning instructions should just increase the stack like function calls.

>  I was about to go for this second option, but I wasn't really sure

I agree. It would be a pity verify the symbolic engine but not use it for the CoLiS macros!

Regarding complex utlities (e.g., mkdir p1 p2 …) I was thinking about a return type of `interp_utility` as `either (set (state, bool)) instruction`. Is this what you have in mind? Are you going to take care of it? In the meantime I could work on the verification of the current symbolic engine with only simple utilities.

**Comment by Niols** [comment]
Hey,

Le 7 février 2019 22:34:05 GMT+01:00, Benedikt Becker <notifications@github.com> a écrit :
>> makes the termination proof complicated if not impossible
>> 
>For termination, we would need a limit the stack size anyway, and
>complex utilities returning instructions should just increase the stack
>like function calls.

That's a pretty good idea! And it gives me hope for the termination proof :-)

>>  I was about to go for this second option, but I wasn't really sure
>>
>I agree. It would be a pity verify the symbolic engine but not use it
>for the CoLiS macros!

Yup!

>Regarding complex utlities (e.g., mkdir p1 p2 …) I was thinking about a
>return type of `interp_utility` as `either (set (state, bool))
>instruction`. Is this what you have in mind? Are you going to take care
>of it? In the meantime I could work on the verification of the current
>symbolic engine with only simple utilities.

That's indeed what I had in mind. I started taking care of it but it's actually a bit more complicated than that. The return type for `interp_utility` would in fact be either `instruction` or `state -> set (state, bool)` which might be annoying for Why3. Also, without your idea of stack with a limit, this modification requires a `diverges` annotation, which is a bit frustrating.

Before working on the proof, shouldn't we take care of the last missing features like the introduction of set -e and set +e in the semantics? (That's a small change.)

-- Nicolas

**Comment by benozol** [comment]
>  hope for the termination proof :-)

Now in #79! Good to go?

> annoying for Why3

Why? Isn’t this just a `match` in the interpretation of utilities? Termination by increasing the stack for interpreting complex utilities, and under-approximation by… the lack of specification of utilities ;)

```ocaml
type simple_utility = state → set (state, bool)
type utility = Simple simple_utility | Complex instruction

val interp_utility : identifier → list string → utility
```

> set -e and set +e

Is this high in the list of blocking missing features?

**Comment by Niols** [comment]
> > hope for the termination proof :-)
> 
> Now in #79! Good to go?

Yes, I'll get to it then.

> > annoying for Why3
> 
> Why? Isn’t this just a `match` in the interpretation of utilities? Termination by increasing the stack for interpreting complex utilities, and under-approximation by… the lack of specification of utilities ;)
> 
> ```ocaml
> type simple_utility = state → set (state, bool)
> type utility = Simple simple_utility | Complex instruction
> 
> val interp_utility : identifier → list string → utility
> ```

That's what I had in mind at first. But then I got stuck. You need the type `utility` to be defined in Why3 because you need the function `call_utility` to look if she got a `Complex` instruction and call the symbolic interpreter recursively in that case. However, it's pretty clear for me how to do it now. I'll try to push a PR today.

> > set -e and set +e
> 
> Is this high in the list of blocking missing features?

I don't know if it is high, but it doesn't seem really complicated to me and since it will change the semantics a little bit, I thought it could break the proof later on.

**Comment by claudemarche** [comment]
> An other way would be to have helpers to compose specifications. And in particular the "if". But that means duplication with the symbolic engine. I was about to go for this second option, but I wasn't really sure. Any thoughts, @claudemarche, @benozol?

I am currently trying to code (in OCaml) the `which` utility. I am trying to support several arguments, which means composing the which with one argument. But I find it fairly easy to do in OCaml: I already had to introduce such a composition operator for `test -a`. So it seems to me that writing those directly in OCaml in fairly easy and indeed certainly easier than to code them in CoLiS: for example I need to split a string along the ':': that exists in OCaml, but I wouldn't be able to do it in CoLiS, and would have to introduce a wrapper.

So, so far, I'm in favor of doing in in OCaml.

**Comment by claudemarche** [comment]
By the way, could we have soon the extension of utilities with environment in the master branch?

**Comment by claudemarche** [comment]
By the by the way, could we have a new rerun of the 'ginette' bench?

**Comment by Niols** [comment]
Doing it in OCaml or supporting CoLiS-script in the symbolic engine is actually an important decision that we have to take before going further. I was under the impression that we were going for the latter. At least, that's what I understood in @benozol's:

> I agree. It would be a pity verify the symbolic engine but not use it for the CoLiS macros!

Also, it would be closer to the paper document. I was ready to start working on the PR to provide CoLiS-scripts in the symbolic engine (it should be feasible for today). But it's an important change. And if it is of no use, there is no need for me to add this.

So: what do we do?

**Comment by claudemarche** [comment]
> So: what do we do?

Needs more discussion. We can discuss that on Wednesday.

**Comment by Niols** [comment]
About the ginette bench, it's done. But did you want it on an other branch of CoLiS-language? I ran it on master.

**Comment by Niols** [comment]
Environment in `interp_program` should arrive shortly. There is just a small thing to solve first. We are discussion it with @benozol in #76.
