### ISSUE TITLE
master branch does not compile on my machine

### ISSUE THREAD

**Issue by yurug** [colis-anr/colis-language#83]
I get this message when compiling the current master branch:
```
File "src/why3/symbolicInterpreter__Results.ml", line 39, characters 31-33:
Error: This expression has type unit but an expression was expected of type
         Colis__SymbolicInterpreter__State.state
make: *** [Makefile:10: build] Error 1
```
Any idea @benozol @Niols?

**Comment by Niols** [comment]
If I'm not mistaken, that's a bug in Why3 that has been by Claude. Update your pin depends and it should be fine!

**Comment by benozol** [comment]
Hi @Niols I am having problems compiling colis with morbig and morsmall pined to the latest master, as stated in the opam file. Did either of the libraries change? Do we have to pin specific versions or repeat "fix translation for newer morbig"?

```
File "src/language/fromShell.ml", line 134, characters 5-12:
Error: Unbound constructor Literal
Hint: Did you mean WLiteral?
```

**Comment by Niols** [comment]
Aaah. You're right. I made changes in Morsmall to provide functionalities in Lintshell and didn't propagate the change in CoLiS-language.

**Comment by Niols** [comment]
(last commit on master should fix this)

**Comment by treinen** [comment]
it compiles on my machine (after having replaced the debian package of morsmall by the latest version in git)
