### ISSUE TITLE
we need an ocaml-dpkg

### ISSUE THREAD

**Issue by treinen** [colis-anr/colis-language#89]
we need ocaml binding to the dpkg-lib, at least for the functionalities of dpkg that we use in the symbolic machine. This includes at least the parameters --validate-version and -- compare-version.

This is in fact an independent project.

**Comment by Niols** [comment]
Yes, I'm going to take that one.

**Comment by Niols** [comment]
First draft:

https://github.com/colis-anr/ocaml-libdpkg
