### ISSUE TITLE
Organize tests

### ISSUE THREAD

**Issue by benozol** [colis-anr/colis-language#9]
The branch `fully-imperative-concrete` contains a directory `tests` with colis scripts and oracle files, and a shell script `run_tests.sh` to compare the execution of scripts with their oracle, for all `tests/*.cls`.

The branch `from-colis` uses files under `examples/shell/` for testing.

Should we create a single command to run the parsing tests and the execution tests?

**Comment by Niols** [comment]
There is already a single command to run tests, which is `dune runtest`. We can also have `make test` that just runs that. Then, we can put tests at several places in the repository (including inline tests in the code) and they will all be detected an run by dune (provided we give it the right `dune` files).

There might be a difference between examples and tests when tests are here for precise tests cases and examples are here to show how to tool is supposed to work. However, for now, I guess that everything can go in `tests/`? But maybe `tests/shell`, `tests/colis`, `tests/...`

Also, what do you think of having the `test` command using Why3 to check the proofs? Then, maybe not `make tests` but `make checks`? Or maybe we could have `make tests` for "regular" tests, `make check-proofs` for Why3 proofs and `make checks` that depends on them both?
