### ISSUE TITLE
initial environment 

### ISSUE THREAD

**Issue by treinen** [colis-anr/colis-language#90]
we need a way to pass to the symbolic engine an initial enviroment (= binding of some environment variables).  The dpkg-maintscript-helper utility, for instance, uses the environment variables DPKG_MAINTSCRIPT_NAME and DPKG_MAINTSCRIPT_PACKAGE.

**Comment by benozol** [comment]
Variables can already be passed to concrete and symbolic interpreter in the CoLiS utility using the command line syntax `--var VARIABLE=VALUE`. Here an example (including arguments):
```shell
$ cat test.sh
echo $1/$2/$a/$b
$ ./bin/colis --var a=X --var b=B --var a=A test.sh one -- --two
one/--two/A/B
```

**Comment by treinen** [comment]
OK so this a rather a TODO for the wrapper that orchestrates symbolic execution on a corpus odf maintainer scripts.

**Comment by treinen** [comment]
Transferred this bug to colis-batch.
