### ISSUE TITLE
create a module per utility

### ISSUE THREAD

**Issue by treinen** [colis-anr/colis-language#91]
we should have a module per utility in the symbolic execution, not everything in one big file

**Comment by treinen** [comment]
I would suggest naming each of these modules like the utility, with one exported function

````
interprete: env -> args -> utility
````

see dpkg-maintscript-helper on the master branch.

**Comment by treinen** [comment]
This should be done for all the utilities at once in order to avoid cyclic dependencies between modules (since one utility may make use of other utilities)

**Comment by benozol** [comment]
Solved by b9c76d51c803c294eba949b5c2377b0ad3c992b5
