### ISSUE TITLE
reading in a saved contents; implement dpkg -L

### ISSUE THREAD

**Issue by treinen** [colis-anr/colis-language#98]
Please add a command line switch to specifiy a saved Contents file. This contents file should then be read in using the function Contents.load. This will allow for the implementation of the dpkg -L command.

**Comment by Niols** [comment]
This is actually only required in Batch, that should set the right filesystem for Colis-Language, no?

**Comment by treinen** [comment]
yes the idea is that colis-batch creats that file and passes to colis-language the name of the file. There is also a corresponding issur against colis-batch for that. 

That means that colis-language should probably do something sensible when that option is not provided.

**Comment by benozol** [comment]
Related: The colis utility takes now an argument `--add-symbolic-fs FILE` which reads the description of a filesystem from FILE and adds it to the initial state. Multiple arguments are combined.
```shell
$ cat simple.fs
/bin/
/bin/sleep
/sbin/
/usr/bin/
/usr/sbin/
/usr/local/lib/
/etc/
/usr/lib/
/var/lib/
/run/
$ ./bin/colis --run-symbolic --add-symbolic-fs simple.fs <(echo 'test -f /bin/sleep')
* Initial states
- id: initial-1
  root: r₁
  clause: ∃ lib₄, var₅, sbin₈, lib₁₁, local₁₂, lib₁₄, bin₁₆, usr₁₇, sbin₁₉, run₂₁, etc₂₃, sleep₂₆, bin₂₇⋅ r₁[bin]bin₂₇ ∧ r₁[etc]etc₂₃ ∧ r₁[run]run₂₁ ∧ r₁[sbin]sbin₁₉ ∧ r₁[usr]usr₁₇ ∧ r₁[var]var₅ ∧ var₅[lib]lib₄ ∧ local₁₂[lib]lib₁₁ ∧ usr₁₇[bin]bin₁₆ ∧ usr₁₇[lib]lib₁₄ ∧ usr₁₇[local]local₁₂ ∧ usr₁₇[sbin]sbin₈ ∧ bin₂₇[sleep]sleep₂₆ ∧ dir(lib₄) ∧ dir(var₅) ∧ dir(sbin₈) ∧ dir(lib₁₁) ∧ dir(local₁₂) ∧ dir(lib₁₄) ∧ dir(bin₁₆) ∧ dir(usr₁₇) ∧ dir(sbin₁₉) ∧ dir(run₂₁) ∧ dir(etc₂₃) ∧ reg(sleep₂₆) ∧ dir(bin₂₇) ∧ sleep₂₆[∅]
  
* Success states
- id: success-1
  root: r₂₈
  clause: ∃ lib₄, var₅, sbin₈, lib₁₁, local₁₂, lib₁₄, bin₁₆, usr₁₇, sbin₁₉, run₂₁, etc₂₃, bin₃₃, sleep₃₄⋅ r₁ = r₂₈ ∧ r₁[bin]bin₃₃ ∧ r₁[etc]etc₂₃ ∧ r₁[run]run₂₁ ∧ r₁[sbin]sbin₁₉ ∧ r₁[usr]usr₁₇ ∧ r₁[var]var₅ ∧ var₅[lib]lib₄ ∧ local₁₂[lib]lib₁₁ ∧ usr₁₇[bin]bin₁₆ ∧ usr₁₇[lib]lib₁₄ ∧ usr₁₇[local]local₁₂ ∧ usr₁₇[sbin]sbin₈ ∧ bin₃₃[sleep]sleep₃₄ ∧ dir(lib₄) ∧ dir(var₅) ∧ dir(sbin₈) ∧ dir(lib₁₁) ∧ dir(local₁₂) ∧ dir(lib₁₄) ∧ dir(bin₁₆) ∧ dir(usr₁₇) ∧ dir(sbin₁₉) ∧ dir(run₂₁) ∧ dir(etc₂₃) ∧ dir(bin₃₃) ∧ reg(sleep₃₄) ∧ sleep₃₄[∅]
  stdout: |
    [UTL] test -f /bin/sleep: path resolves to a regular file

* Summary
- Success cases: 1
- Error cases: 0
- Incomplete symbolic execution: 0

```
 @Niols maybe you can reuse something from https://github.com/colis-anr/colis-language/blob/master/src/symbolic/filesystemSpec.mli

**Comment by Niols** [comment]
This is being taken care of in colis-batch.
